language: node_js
cache: npm
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '8'
script:
  - yarn test:prod || exit 0
jobs:
  include:
    # - stage: coverage
    #   node_js: '11'
    #   script: yarn report-coverage
    - stage: release
      if: branch = master
      node_js: '11'
      script: yarn build && semantic-release
      # deploy:
      #   provider: npm
      #   email: $NPM_EMAIL
      #   api_key: $NPM_API_KEY
# after_success:
#   - npm run travis-deploy-once "npm run report-coverage"
#   - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi
#   - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
